# Generated by Django 4.1.3 on 2023-01-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uid',
            field=models.CharField(max_length=1000),
        ),
    ]
